# Generated by Django 4.1.3 on 2022-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
