# Generated by Django 4.1.3 on 2022-12-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_job_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created',
        ),
    ]
